from g4f.client import Client
import gradio as gr

# Initialize the client to interact with the GPT-4 model
client = Client()

# Function to generate chatbot response based on topic and skill level
def chatbot_response(topic, skill_level):
    # Create a prompt using the topic and skill level
    prompt = f"Topic: {topic}\nSkill Level: {skill_level}\nProvide information about {topic} suitable for {skill_level} level."
    
    # Call the GPT-4 model to generate the response
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
    )
    
    # Return the response generated by the chatbot
    return response.choices[0].message.content

# Gradio interface with topic input and skill level selection
interface = gr.Interface(
    fn=chatbot_response,
    inputs=[
        gr.Textbox(lines=2, placeholder="Enter your topic (e.g., Pongal)"),  # Topic input
        gr.Dropdown(choices=["Beginner", "Intermediate", "Expert"], label="Select Skill Level")  # Skill level dropdown
    ],
    outputs="text",  # Output response from chatbot
    title="AI Chatbot",
    description="Enter a topic, then select your skill level to receive a customized response."
)

if __name__ == '__main__':
    interface.launch()
